export const bedsNumberIdPrefix = 'beds-fltr-'
export const bathsValuesPrefix = 'baths-filter-btn-'
export const homeTypeIdPrefix = 'home-type-'
export const soldDateRangeIdPrefix = 'sold-last-'
export const forSaleRentSoldIdPrefix = 'all-filters-btn-'
