export const stateCodes = [
  { AL: 'Alabama' },
  { AK: 'Alaska' },
  { AZ: 'Arizona' },
  { AR: 'Arkansas' },
  { CA: 'California' },
  { CO: 'Colorado' },
  { CT: 'Connecticut' },
  { DE: 'Delaware' },
  { DC: 'District Of Columbia' },
  { FL: 'Florida' },
  { GA: 'Georgia' },
  { HI: 'Hawaii' },
  { ID: 'Idaho' },
  { IL: 'Illinois' },
  { IN: 'Indiana' },
  { IA: 'Iowa' },
  { KS: 'Kansas' },
  { KY: 'Kentucky' },
  { LA: 'Louisiana' },
  { ME: 'Maine' },
  { MD: 'Maryland' },
  { MA: 'Massachusetts' },
  { MI: 'Michigan' },
  { MN: 'Minnesota' },
  { MS: 'Mississippi' },
  { MO: 'Missouri' },
  { MT: 'Montana' },
  { NE: 'Nebraska' },
  { NV: 'Nevada' },
  { NH: 'New Hampshire' },
  { NJ: 'New Jersey' },
  { NM: 'New Mexico' },
  { NY: 'New York' },
  { NC: 'North Carolina' },
  { ND: 'North Dakota' },
  { OH: 'Ohio' },
  { OK: 'Oklahoma' },
  { OR: 'Oregon' },
  { PA: 'Pennsylvania' },
  { RI: 'Rhode Island' },
  { SC: 'South Carolina' },
  { SD: 'South Dakota' },
  { TN: 'Tennessee' },
  { TX: 'Texas' },
  { UT: 'Utah' },
  { VT: 'Vermont' },
  { VA: 'Virginia' },
  { WA: 'Washington' },
  { WV: 'West Virginia' },
  { WI: 'Wisconsin' },
  { WY: 'Wyoming' },
]

export const topTenCitiesByState = [
  {
    id: 'AL',
    name: 'Alabama',
    cities: [
      'Birmingham',
      'Montgomery',
      'Mobile',
      'Huntsville',
      'Tuscaloosa',
      'Hoover',
      'Dothan',
      'Decatur',
      'Auburn',
      'Gadsden',
    ],
  },
  {
    id: 'AK',
    name: 'Alaska',
    cities: [
      'Anchorage',
      'Juneau',
      'Fairbanks',
      'Sitka',
      'Ketchikan',
      'Kenai',
      'Kodiak',
      'Bethel',
      'Wasilla',
      'Barrow',
    ],
  },
  {
    id: 'AZ',
    name: 'Arizona',
    cities: [
      'Phoenix',
      'Tucson',
      'Mesa',
      'Glendale',
      'Scottsdale',
      'Chandler',
      'Tempe',
      'Gilbert',
      'Peoria',
      'Yuma',
    ],
  },
  {
    id: 'AK',
    name: 'Arkansas',
    cities: [
      'Little Rock',
      'Fort Smith',
      'North Little Rock',
      'Fayetteville',
      'Jonesboro',
      'Pine Bluff',
      'Springdale',
      'Conway',
      'Rogers',
      'Hot Springs',
    ],
  },
  {
    id: 'CA',
    name: 'California',
    cities: [
      'Los Angeles',
      'San Diego',
      'San Jose',
      'San Francisco',
      'Long Beach',
      'Fresno',
      'Sacramento',
      'Oakland',
      'Santa Ana',
      'Anaheim',
    ],
  },
  {
    id: 'CO',
    name: 'Colorado',
    cities: [
      'Denver',
      'Colorado Springs',
      'Aurora',
      'Lakewood',
      'Fort Collins',
      'Arvada',
      'Pueblo',
      'Westminster',
      'Boulder',
      'Thornton',
    ],
  },
  {
    id: 'CT',
    name: 'Connecticut',
    cities: [
      'Bridgeport',
      'New Haven',
      'Hartford',
      'Stamford',
      'Waterbury',
      'Norwalk',
      'Danbury',
      'New Britain',
      'West Hartford',
      'Greenwich',
    ],
  },
  {
    id: 'DE',
    name: 'Delaware',
    cities: [
      'Wilmington',
      'Dover',
      'Newark',
      'Milford',
      'Seaford',
      'Middletown',
      'Elsmere',
      'Smyrna',
      'New Castle',
      'Georgetown',
    ],
  },
  {
    id: 'FL',
    name: 'Florida',
    cities: [
      'Jacksonville',
      'Miami',
      'Tampa',
      'St. Petersburg',
      'Hialeah',
      'Orlando',
      'Fort Lauderdale',
      'Tallahassee',
      'Hollywood',
      'Pembroke Pines',
    ],
  },
  {
    id: 'GA',
    name: 'Georgia',
    cities: [
      'Atlanta',
      'Augusta-Richmond County',
      'Columbus',
      'Savannah',
      'Athens-Clarke County',
      'Macon',
      'Roswell',
      'Albany',
      'Marietta',
      'Warner Robins',
    ],
  },

  {
    id: 'HI',
    name: 'Hawaii',
    cities: [
      'Honolulu',
      'Hilo',
      'Kailua',
      'Kaneohe',
      'Waipahu',
      'Pearl City',
      'Waimalu',
      'Mililani Town',
      'Kahului',
      'Kihei',
    ],
  },
  {
    id: 'ID',
    name: 'Idaho',
    cities: [
      'Boise',
      'Nampa',
      'Pocatello',
      'Idaho Falls',
      'Meridian',
      "Coeur d'Alene",
      'Twin Falls',
      'Lewiston',
      'Caldwell',
      'Moscow',
    ],
  },
  {
    id: 'IL',
    name: 'Illinois',
    cities: [
      'Chicago',
      'Rockford',
      'Aurora',
      'Naperville',
      'Peoria',
      'Springfield',
      'Joliet',
      'Elgin',
      'Waukegan',
      'Cicero',
    ],
  },
  {
    id: 'IN',
    name: 'Indiana',
    cities: [
      'Indianapolis',
      'Fort Wayne',
      'Evansville',
      'South Bend',
      'Gary',
      'Hammond',
      'Bloomington',
      'Muncie',
      'Anderson',
      'Terre Haute',
    ],
  },
  {
    id: 'IA',
    name: 'Iowa',
    cities: [
      'Des Moines',
      'Cedar Rapids',
      'Davenport',
      'Sioux City',
      'Waterloo',
      'Iowa City',
      'Council Bluffs',
      'Dubuque',
      'Ames',
      'West Des Moines',
    ],
  },
  {
    id: 'KS',
    name: 'Kansas',
    cities: [
      'Wichita',
      'Overland Park',
      'Kansas City',
      'Topeka',
      'Olathe',
      'Lawrence',
      'Shawnee',
      'Salina',
      'Manhattan',
      'Hutchinson',
    ],
  },
  {
    id: 'KY',
    name: 'Kentucky',
    cities: [
      'Lexington-Fayette',
      'Louisville',
      'Owensboro',
      'Bowling Green',
      'Covington',
      'Hopkinsville',
      'Frankfort',
      'Henderson',
      'Richmond',
      'Jeffersontown',
    ],
  },
  {
    id: 'LA',
    name: 'Louisiana',
    cities: [
      'New Orleans',
      'Baton Rouge',
      'Shreveport',
      'Lafayette',
      'Lake Charles',
      'Kenner',
      'Bossier City',
      'Monroe',
      'Alexandria',
      'New Iberia',
    ],
  },
  {
    id: 'ME',
    name: 'Maine',
    cities: [
      'Portland',
      'Lewiston',
      'Bangor',
      'South Portland',
      'Auburn',
      'Brunswick',
      'Biddeford',
      'Sanford',
      'Augusta',
      'Scarborough',
    ],
  },
  {
    id: 'MD',
    name: 'Maryland',
    cities: [
      'Baltimore',
      'Frederick',
      'Gaithersburg',
      'Bowie',
      'Rockville',
      'Hagerstown',
      'Annapolis',
      'College Park',
      'Salisbury',
      'Cumberland',
    ],
  },

  {
    id: 'MA',
    name: 'Massachusetts',
    cities: [
      'Boston',
      'Worcester',
      'Springfield',
      'Lowell',
      'Cambridge',
      'Brockton',
      'New Bedford',
      'Fall River',
      'Lynn',
      'Quincy',
    ],
  },
  {
    id: 'MI',
    name: 'Michigan',
    cities: [
      'Detroit',
      'Grand Rapids',
      'Warren',
      'Flint',
      'Sterling Heights',
      'Lansing',
      'Ann Arbor',
      'Livonia',
      'Dearborn',
      'Westland',
    ],
  },
  {
    id: 'MN',
    name: 'Minnesota',
    cities: [
      'Minneapolis',
      'St. Paul',
      'Duluth',
      'Rochester',
      'Bloomington',
      'Brooklyn Park',
      'Plymouth',
      'Eagan',
      'Coon Rapids',
      'Burnsville',
    ],
  },
  {
    id: 'MS',
    name: 'Mississippi',
    cities: [
      'Jackson',
      'Gulfport',
      'Biloxi',
      'Hattiesburg',
      'Greenville',
      'Meridian',
      'Tupelo',
      'Southaven',
      'Vicksburg',
      'Pascagoula',
    ],
  },
  {
    id: 'MO',
    name: 'Missouri',
    cities: [
      'Kansas City',
      'St. Louis',
      'Springfield',
      'Independence',
      'Columbia',
      'St. Joseph',
      "Lee's Summit",
      'St. Charles',
      'St. Peters',
      'Florissant',
    ],
  },
  {
    id: 'MT',
    name: 'Montana',
    cities: [
      'Billings',
      'Missoula',
      'Great Falls',
      'Butte-Silver Bow',
      'Bozeman',
      'Helena',
      'Kalispell',
      'Havre',
      'Anaconda-Deer Lodge County',
      'Miles City',
    ],
  },
  {
    id: 'NE',
    name: 'Nebraska',
    cities: [
      'Omaha',

      'Lincoln',

      'Bellevue',

      'Grand Island',

      'Kearney',

      'Fremont',

      'Hastings',

      'North Platte',

      'Norfolk',

      'Columbus',
    ],
  },
  {
    id: 'NV',
    name: 'Nevada',
    cities: [
      'Las Vegas',
      'Reno',
      'Henderson',
      'North Las Vegas',
      'Sparks',
      'Carson City',
      'Elko',
      'Boulder City',
      'Mesquite',
      'Fallon',
    ],
  },
  {
    id: 'NH',
    name: 'New Hampshire',
    cities: [
      'Manchester',
      'Nashua',
      'Concord',
      'Derry',
      'Rochester',
      'Salem',
      'Dover',
      'Merrimack',
      'Londonderry',
      'Hudson',
    ],
  },
  {
    id: 'NJ',
    name: 'New Jersey',
    cities: [
      'Newark',
      'Jersey City',
      'Paterson',
      'Elizabeth',
      'Edison',
      'Woodbridge',
      'Dover',
      'Hamilton',
      'Trenton',
      'Camden',
    ],
  },

  {
    id: 'NM',
    name: 'New Mexico',
    cities: [
      'Albuquerque',
      'Las Cruces',
      'Santa Fe',
      'Rio Rancho',
      'Roswell',
      'Farmington',
      'Alamogordo',
      'Clovis',
      'Hobbs',
      'Carlsbad',
    ],
  },
  {
    id: 'NY',
    name: 'New York',
    cities: [
      'New York',
      'Buffalo',
      'Rochester',
      'Yonkers',
      'Syracuse',
      'Albany',
      'New Rochelle',
      'Mount Vernon',
      'Schenectady',
      'Utica',
    ],
  },
  {
    id: 'NC',
    name: 'North Carolina',
    cities: [
      'Charlotte',
      'Raleigh',
      'Greensboro',
      'Durham',
      'Winston-Salem',
      'Fayetteville',
      'Cary',
      'High Point',
      'Wilmington',
      'Asheville',
    ],
  },
  {
    id: 'ND',
    name: 'North Dakota',
    cities: [
      'Fargo',
      'Bismarck',
      'Grand Forks',
      'Minot',
      'Mandan',
      'Dickinson',
      'Jamestown',
      'West Fargo',
      'Williston',
      'Wahpeton',
    ],
  },
  {
    id: 'OH',
    name: 'Ohio',
    cities: [
      'Columbus',
      'Cleveland',
      'Cincinnati',
      'Toledo',
      'Akron',
      'Dayton',
      'Parma',
      'Youngstown',
      'Canton',
      'Lorain',
    ],
  },
  {
    id: 'OK',
    name: 'Oklahoma',
    cities: [
      'Oklahoma City',
      'Tulsa',
      'Norman',
      'Lawton',
      'Broken Arrow',
      'Edmond',
      'Midwest City',
      'Enid',
      'Moore',
      'Stillwater',
    ],
  },
  {
    id: 'OR',
    name: 'Oregon',
    cities: [
      'Portland',
      'Eugene',
      'Salem',
      'Gresham',
      'Beaverton',
      'Hillsboro',
      'Medford',
      'Springfield',
      'Bend',
      'Corvallis',
    ],
  },
  {
    id: 'PA',
    name: 'Pennsylvania',
    cities: [
      'Philadelphia',
      'Pittsburgh',
      'Allentown',
      'Erie',
      'Upper Darby',
      'Reading',
      'Scranton',
      'Bethlehem',
      'Lower Merion',
      'Bensalem',
    ],
  },
  {
    id: 'RI',
    name: 'Rhode Island',
    cities: [
      'Providence',
      'Warwick',
      'Cranston',
      'Pawtucket',
      'East Providence',
      'Woonsocket',
      'Coventry',
      'North Providence',
      'Cumberland',
      'West Warwick',
    ],
  },
  {
    id: 'SC',
    name: 'South Carolina',
    cities: [
      'Columbia',
      'Charleston',
      'North Charleston',
      'Greenville',
      'Rock Hill',
      'Mount Pleasant',
      'Spartanburg',
      'Sumter',
      'Hilton Head Island',
      'Florence',
    ],
  },

  {
    id: 'SD',
    name: 'South Dakota',
    cities: [
      'Sioux Falls',
      'Rapid City',
      'Aberdeen',
      'Watertown',
      'Brookings',
      'Mitchell',
      'Pierre',
      'Yankton',
      'Huron',
      'Vermillion',
    ],
  },
  {
    id: 'TN',
    name: 'Tennessee',
    cities: [
      'Memphis',
      'Nashville-Davidson',
      'Knoxville',
      'Chattanooga',
      'Clarksville',
      'Murfreesboro',
      'Jackson',
      'Johnson City',
      'Kingsport',
      'Franklin',
    ],
  },
  {
    id: 'TX',
    name: 'Texas',
    cities: [
      'Houston',
      'Dallas',
      'San Antonio',
      'Austin',
      'El Paso',
      'Fort Worth',
      'Arlington',
      'Corpus Christi',
      'Plano',
      'Garland',
    ],
  },
  {
    id: 'UT',
    name: 'Utah',
    cities: [
      'Salt Lake City',
      'West Valley City',
      'Provo',
      'Sandy',
      'Orem',
      'Ogden',
      'West Jordan',
      'Layton',
      'Taylorsville',
      'St. George',
    ],
  },
  {
    id: 'VT',
    name: 'Vermont',
    cities: [
      'Burlington',
      'Essex',
      'Rutland',
      'Colchester',
      'South Burlington',
      'Bennington',
      'Brattleboro',
      'Hartford',
      'Milton',
      'Barre',
    ],
  },
  {
    id: 'VA',
    name: 'Virginia',
    cities: [
      'Virginia Beach',
      'Norfolk',
      'Chesapeake',
      'Richmond',
      'Newport News',
      'Hampton',
      'Alexandria',
      'Portsmouth',
      'Roanoke',
      'Lynchburg',
    ],
  },
  {
    id: 'WA',
    name: 'Washington',
    cities: [
      'Seattle',
      'Spokane',
      'Tacoma',
      'Vancouver',
      'Bellevue',
      'Everett',
      'Federal Way',
      'Kent',
      'Yakima',
      'Bellingham',
    ],
  },
  {
    id: 'WV',
    name: 'West Virginia',
    cities: [
      'Charleston',
      'Huntington',
      'Parkersburg',
      'Wheeling',
      'Morgantown',
      'Weirton',
      'Fairmont',
      'Beckley',
      'Clarksburg',
      'Martinsburg',
    ],
  },
  {
    id: 'WI',
    name: 'Wisconsin',
    cities: [
      'Milwaukee',
      'Madison',
      'Green Bay',
      'Kenosha',
      'Racine',
      'Appleton',
      'Waukesha',
      'Oshkosh',
      'Eau Claire',
      'West Allis',
    ],
  },
  {
    id: 'WY',
    name: 'Wyoming',
    cities: [
      'Cheyenne',

      'Casper',

      'Laramie',

      'Gillette',

      'Rock Springs',

      'Sheridan',

      'Green River',

      'Evanston',

      'Riverton',

      'Cody',
    ],
  },
]
